# add the following to _config.yml file
title: Berend Driessen
#theme: jekyll-theme-minimal

remote_theme: pages-themes/minimal@v0.2.0

title: "Berend Driessen"
description: "Portfolio, projecten en blog"
url: "https://<username>.github.io"
baseurl: ""          # bij projectsite: "/<repo-naam>"

remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  # Optioneel als je README als index wilt gebruiken:
  # - jekyll-readme-index

paginate: 5
paginate_path: "/blog/page:num"

collections:
  notes:
    output: true
    permalink: /notes/:name/

# Let op: jekyll-theme-minimal heeft géén post/page layouts; gebruik 'default'
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: default
  - scope:
      path: ""
      type: "notes"
    values:
      layout: default

      path: ""
      type: "notes"
    values:
      layout: page
